### ISSUE TITLE
"Whatsapp Desktop" menu on Windows version gives Java errors

### ISSUE THREAD

**Issue by Jamushroom** [bcalik/Whatsapp-Desktop#21]
Each menu item in this menu is giving Java errors whenever the user tries to use one of them.

**Comment by ghost** [comment]
I also have the same issue. Can this easily be resolved?

**Comment by francwalter** [comment]
Is there any other clone of WhatsApp Desktop on Github working bugfree on Windows 8.1?
I use Waow, but this is also abandoned and not that stable.
Thank's

**Comment by Jamushroom** [comment]
Check out this one: https://github.com/Aluxian/Whatsie

**Comment by bcalik** [comment]
Could you please test the latest version:
https://github.com/bcalik/Whatsapp-Desktop/releases/tag/v0.3.2

**Comment by francwalter** [comment]
Seems to work! Thank!
Will try it for a whyle and abandon the abandoned Waow.
The settings dialog is a bit strange, look:

![graphic_29_04_2016 15_49_19](https://cloud.githubusercontent.com/assets/927269/14918090/67298f40-0e22-11e6-8858-5f0b842da963.jpg)

the "50" is only visible because selected. All is strangely black.
But this is cosmetics and wont bother me to test.

@Jamushroom Thank for the Hint with Aluxians Whatsie, its more features even, will try this also. Aluxian had not done development for a while before, but this now good!
EDIT: I mixed it up, I ment Aluxian's WhatsApp-Desktop, which is untouched since last year. Whatsie is under heavy development seems :)
