### ISSUE TITLE
Settings window is totally garbled

### ISSUE THREAD

**Issue by variadico** [bcalik/Whatsapp-Desktop#37]
![whatsapp-desktop](https://cloud.githubusercontent.com/assets/4296393/22137439/f4dd598c-de8f-11e6-8841-79b925584feb.png)

OS: Arch Linux
Computer: Dell XPS 13 9360 HiDPI
Desktop Environment: Gnome 3

**Comment by awesmubarak** [comment]
It gets worse.

This is what happens if you maximise, then minimize the window: 
![image](https://cloud.githubusercontent.com/assets/24862378/22901760/a590902a-f22a-11e6-8dbe-109281a4a7f7.png)

And this is what heappens when settings are changed:
![image](https://cloud.githubusercontent.com/assets/24862378/22901856/fe40666e-f22a-11e6-8e0e-4039201f4c94.png)

OS: Ubuntu 16.10
Desktop enviroment: KDE5

Since we're both using linux, someone using windows or osx should attempt to reproduce.

**Comment by fabmazz** [comment]
This affects me also, using Archlinux and whatsapp-desktop aur package, and Intel i7 skylake processor and graphics
![screenshot_20170319_123400](https://cloud.githubusercontent.com/assets/14214829/24080489/b75c2d1a-0ca0-11e7-85e8-acc47a6b7407.png)

**Comment by bcalik** [comment]
Please try latest version: https://github.com/bcalik/Whatsapp-Desktop/releases/tag/v0.3.3

**Comment by awesmubarak** [comment]
Thanks a lot, but I don't think this has helped. Loading the settings page reults in this:

![image](https://cloud.githubusercontent.com/assets/24862378/26276095/1013cc8e-3d60-11e7-9f2c-5814532e88f5.png)

Full screening does this:

![image](https://cloud.githubusercontent.com/assets/24862378/26276105/3606803a-3d60-11e7-808b-04b2069e437c.png)

Full-screening and minimizing does this:

![image](https://cloud.githubusercontent.com/assets/24862378/26276102/24a83cf2-3d60-11e7-817b-e2c5a4820568.png)


The background color somethimes changes to white, whithout much of a pattern:

![image](https://cloud.githubusercontent.com/assets/24862378/26276125/a85ecf70-3d60-11e7-9ea4-fa859bef33de.png)

Still using Ubuntu with KDE desktop.

**Comment by dayfuaim** [comment]
I confirm this on Ubuntu 17.04.
Still have place.
