### ISSUE TITLE
Linux executable

### ISSUE THREAD

**Issue by simonbcn** [bcalik/Whatsapp-Desktop#5]
Ubuntu 14.04 64 bits

I have added the following lines to package.json:

```
...
    "clean:linux": "rm -rf ./dist/linux",
...
    "build:linux": "npm run clean:linux && electron-packager ./app \"Whatsapp\" --out=dist/linux --platform=linux --arch=x64 --version=0.30.0"
...
```

It creates the files correctly but when I execute, it opens a borderless window:
![20150805_17 23 23_01](https://cloud.githubusercontent.com/assets/428231/9089714/d5b56aa6-3b96-11e5-8219-2c7160409173.jpg)

and it doesn't show any icon in Unity launcher:
![20150805_17 25 33_01](https://cloud.githubusercontent.com/assets/428231/9089763/17efe68a-3b97-11e5-8a7f-28317cfb3664.jpg)

**Comment by championswimmer** [comment]
I am on this :) 
Have some linux electron apps under my belt. Expect a PR in a day or two :wink:

**Comment by orschiro** [comment]
That's great news. 

Thank you @championswimmer!

~Robert

**Comment by bcalik** [comment]
Could you please test the latest version:
https://github.com/bcalik/Whatsapp-Desktop/releases/tag/v0.3.2

**Comment by orschiro** [comment]
@bcalik,

Would it be possible to provide a deb installer package?

Thankfully,

~Robert

**Comment by championswimmer** [comment]
Hi,

I'll put that up by tomorrow. I am running Linux. I can build a deb and a
rpm.

**Comment by orschiro** [comment]
Dear @Arnav,

That would be fantastic, thank you!

~Robert

Sent from [Nylas N1](https://nylas.com/n1?ref=n1), the extensible, open source
mail client.  

On Apr 7 2016, at 11:46 am, Arnav Gupta &lt;notifications@github.com&gt;
wrote:  

> Hi,  

I'll put that up by tomorrow. I am running Linux. I can build a deb and a  
rpm.  
On 07-Apr-2016 13:34, "Robert Orzanna" &lt;notifications@github.com&gt; wrote:  

&gt; @bcalik &lt;https://github.com/bcalik&gt;,  
&gt;  
&gt; Would it be possible to provide a deb installer package?  
&gt;  
&gt; Thankfully,  
&gt;  
&gt; ~Robert  
&gt;  
&gt; —  
&gt; You are receiving this because you were mentioned.  
&gt; Reply to this email directly or view it on GitHub  
&gt; &lt;https://github.com/bcalik/Whatsapp-
Desktop/issues/5#issuecomment-206749347&gt;  
&gt;

**Comment by championswimmer** [comment]
@orschiro 

It'll take some time. Maybe a couple of days. I am working on integrating electron-builder into this, so installers for Windows + Mac + Linux all are generated.

**Comment by orschiro** [comment]
@Arnav,

Absolutely no problem. Thanks for keeping us updated on this!

~Robert

Sent from [Nylas N1](https://nylas.com/n1?ref=n1), the extensible, open source
mail client.
